Integrate concourse
concourse/voyager pull request #2
Opened 2019-08-09 20:00 UTC by ddadlani

This is a draft PR to update Voyager with the things we need for Concourse.

All feedback is welcome.

Docs incoming

2019-08-27 20:06 UTC, vito requested changes
a couple tests failed to compile, otherwise :+1:

2019-08-27 20:06 UTC, vito commented on voyager_test.go
> +			version := migrator.SupportedVersion(logger)
```
./voyager_test.go:134:12: assignment mismatch: 1 variable but migrator.SupportedVersion returns 2 values
```

2019-08-27 20:06 UTC, vito commented on voyager_test.go
> +			version := migrator.SupportedVersion(logger)
```
./voyager_test.go:140:12: assignment mismatch: 1 variable but migrator.SupportedVersion returns 2 values
```

2019-08-27 20:09 UTC, ddadlani commented on voyager_test.go
> +			version := migrator.SupportedVersion(logger)
🤦‍♀ I was so focused on functionality, I forgot about tests

2019-09-25 19:23 UTC, vito approved these changes
:+1:

2019-09-26 14:43 UTC, merged

2019-09-26 14:44 UTC, ddadlani commented
we still need to change Concourse to use voyager (it doesn't currently use it, the code is embedded in the Concourse codebase)